### ISSUE TITLE
Liquid syntax error (line 19): Unknown tag 't' in _includes/post.html, included in index.html in Jekyll-3.1.2

### ISSUE THREAD

**Issue by johnliao52** [Anthony-Gaudino/jekyll-multiple-languages-plugin#63]
bundle exec jekyll serve --trace
Configuration file: /home/john/blog/3rd/research/jekyll-multiple-languages-plugin/example/_config.yml
            Source: /home/john/blog/3rd/research/jekyll-multiple-languages-plugin/example
       Destination: /home/john/blog/3rd/research/jekyll-multiple-languages-plugin/example/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Liquid Exception: Liquid syntax error (line 19): Unknown tag 't' in _includes/post.html, included in index.html
/var/lib/gems/2.1.0/gems/jekyll-3.1.2/lib/jekyll/tags/include.rb:132:in `rescue in render': Liquid syntax error (line 19): Unknown tag 't' (Jekyll::Tags::IncludeTagError)
	from /var/lib/gems/2.1.0/gems/jekyll-3.1.2/lib/jekyll/tags/include.rb:124:in `render'
	from /var/lib/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/block.rb:151:in `render_token'
	from /var/lib/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:5:in `block in render_token_with_profiling'
	from /var/lib/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/profiler.rb:80:in `profile_token_render'
	from /var/lib/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:4:in `render_token_with_profiling'
	from /var/lib/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/block.rb:135:in `block in render_all'
	from /var/lib/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `each'
	from /var/lib/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `render_all'
	from /var/lib/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/block.rb:108:in `render'
	from /var/lib/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/template.rb:210:in `block in render'
	from /var/lib/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/template.rb:262:in `with_profiling'
	from /var/lib/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/template.rb:209:in `render'
	from /var/lib/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/template.rb:222:in `render!'
	from /var/lib/gems/2.1.0/gems/jekyll-3.1.2/lib/jekyll/liquid_renderer/file.rb:28:in `block (2 levels) in render!'
	from /var/lib/gems/2.1.0/gems/jekyll-3.1.2/lib/jekyll/liquid_renderer/file.rb:36:in `measure_bytes'
	from /var/lib/gems/2.1.0/gems/jekyll-3.1.2/lib/jekyll/liquid_renderer/file.rb:27:in `block in render!'
	from /var/lib/gems/2.1.0/gems/jekyll-3.1.2/lib/jekyll/liquid_renderer/file.rb:43:in `measure_time'
	from /var/lib/gems/2.1.0/gems/jekyll-3.1.2/lib/jekyll/liquid_renderer/file.rb:26:in `render!'
	from /var/lib/gems/2.1.0/gems/jekyll-3.1.2/lib/jekyll/renderer.rb:106:in `render_liquid'
	from /var/lib/gems/2.1.0/gems/jekyll-3.1.2/lib/jekyll/renderer.rb:61:in `run'
	from /var/lib/gems/2.1.0/gems/jekyll-3.1.2/lib/jekyll/site.rb:179:in `block in render'
	from /var/lib/gems/2.1.0/gems/jekyll-3.1.2/lib/jekyll/site.rb:177:in `each'
	from /var/lib/gems/2.1.0/gems/jekyll-3.1.2/lib/jekyll/site.rb:177:in `render'
	from /var/lib/gems/2.1.0/gems/jekyll-3.1.2/lib/jekyll/site.rb:59:in `process'
	from /var/lib/gems/2.1.0/gems/jekyll-3.1.2/lib/jekyll/command.rb:26:in `process_site'
	from /var/lib/gems/2.1.0/gems/jekyll-3.1.2/lib/jekyll/commands/build.rb:60:in `build'
	from /var/lib/gems/2.1.0/gems/jekyll-3.1.2/lib/jekyll/commands/build.rb:33:in `process'
	from /var/lib/gems/2.1.0/gems/jekyll-3.1.2/lib/jekyll/commands/serve.rb:34:in `block (2 levels) in init_with_program'
	from /usr/lib/ruby/vendor_ruby/mercenary/command.rb:220:in `call'
	from /usr/lib/ruby/vendor_ruby/mercenary/command.rb:220:in `block in execute'
	from /usr/lib/ruby/vendor_ruby/mercenary/command.rb:220:in `each'
	from /usr/lib/ruby/vendor_ruby/mercenary/command.rb:220:in `execute'
	from /usr/lib/ruby/vendor_ruby/mercenary/program.rb:42:in `go'
	from /usr/lib/ruby/vendor_ruby/mercenary.rb:19:in `program'
	from /var/lib/gems/2.1.0/gems/jekyll-3.1.2/bin/jekyll:13:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
john@johnlubuntu:~/blog/3rd/research/jekyll-multiple-languages-plugin/example$

**Comment by Anthony-Gaudino** [comment]
The current version is not compatible with Jekyll 3.1.2.

Version 1.4 of the plugin will come out soon and will be compatible with Jekyll 3.1.2.

You may also want to try this plugin: https://github.com/vwochnik/jekyll-language-plugin

**Comment by Anthony-Gaudino** [comment]
The version 1.4.0 of this plugin was just released with support for Jekyll 3, you can try it and see if it solves your problem.

**Comment by jamesmaniscalco** [comment]
Just as commentary - I had this problem when updating to version 1.4 of the plugin... for me the issue was that the plugin was not being loaded properly (I didn't update the `_plugins/plugins.rb` file correctly). Fixing that file fixed the issue for me.

**Comment by ruan-brandao** [comment]
I have run into this problem trying to deploy a Jekyll site to Github pages. I am using Jekyll 3.8.6 and jekyll-multiple-languages-plugin 1.6.1 (installed via Gemfile)

Is there a solution for this problem?

**Comment by coding-Alice** [comment]
I had the same issue today, and I've been looking for this solution the whole day, and I finally got the solution for this problem! For people who is getting **liquid syntax error Unknown tag 't'**, change the tag t to translate then it will work.

**Comment by AngeloFilaseta** [comment]
Problem still present in Jekyll 3.9.2 and jekyll-multiple-languages-plugin 1.7.0 deploying to github pages. Everything works as expected in a local environment.

**Comment by AngeloFilaseta** [comment]
@ruan-brandao I had the same problem with GitHub Pages. As stated on [Jekyll official website's plugin page](https://jekyllrb.com/docs/plugins/installation/):

> [GitHub Pages](https://pages.github.com/) is powered by Jekyll. All GitHub Pages sites are generated using the --safe option to disable plugins (with the exception of some [whitelisted plugins](https://pages.github.com/versions)) for security reasons. Unfortunately, this means your plugins won't work if you’re deploying via GitHub Pages.
> 
> You can still use GitHub Pages to publish your site, but you’ll need to build the site locally and push the generated files to your GitHub repository instead of the Jekyll source files.

However, it is still possible to use the plugin in github pages, by using to the [jeffreytse/jekyll-deploy-action](https://github.com/jeffreytse/jekyll-deploy-action).
