### ISSUE TITLE
Liquid Exception: invalid byte sequence in US-ASCII when running the example

### ISSUE THREAD

**Issue by renefs** [Anthony-Gaudino/jekyll-multiple-languages-plugin#83]
Hi,

Following all the steps of the README, if I try to run the example I always get the same:

```
➜  example git:(master) bundle exec jekyll serve
Configuration file: /Users/renefernandez/Projects/jekyll-multiple-languages-plugin/example/_config.yml
Configuration file: /Users/renefernandez/Projects/jekyll-multiple-languages-plugin/example/_config.yml
            Source: /Users/renefernandez/Projects/jekyll-multiple-languages-plugin/example
       Destination: /Users/renefernandez/Projects/jekyll-multiple-languages-plugin/example/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
Building site for default language: "it" to: /Users/renefernandez/Projects/jekyll-multiple-languages-plugin/example/_site
Loading translation from file /Users/renefernandez/Projects/jekyll-multiple-languages-plugin/example/_i18n/it.yml
  Liquid Exception: invalid byte sequence in US-ASCII in /_layouts/default.html
jekyll 3.3.1 | Error:  invalid byte sequence in US-ASCII
```

I tried to remove the non-english chars from the spanish and italian translations, but I am still getting this error.

**Comment by bgaillard** [comment]
Hi, we also encounter this error, it's very critical because with this error its impossible to use the plugin.

Here the output we have.

```
bundle exec jekyll serve --trace
Configuration file: D:/workspace/gomoob-website/_config.yml
Configuration file: D:/workspace/gomoob-website/_config.yml
            Source: D:/workspace/gomoob-website
       Destination: D:/workspace/gomoob-website/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
Building site for default language: "fr" to: D:/workspace/gomoob-website/_site
Loading translation from file D:/workspace/gomoob-website/_i18n/fr.yml
  Liquid Exception: incompatible character encodings: UTF-8 and CP850 in /_layouts/default.html
D:/dev_tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/liquid-3.0.6/lib/liquid/block.rb:147:in `join': incompatible character encodings: UTF-8 and CP850 (Encoding::CompatibilityError)
        from D:/dev_tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/liquid-3.0.6/lib/liquid/block.rb:147:in `render_all'
        from D:/dev_tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/liquid-3.0.6/lib/liquid/block.rb:108:in `render'
        from D:/dev_tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/liquid-3.0.6/lib/liquid/template.rb:210:in `block in render'
        from D:/dev_tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/liquid-3.0.6/lib/liquid/template.rb:262:in `with_profiling'
        from D:/dev_tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/liquid-3.0.6/lib/liquid/template.rb:209:in `render'
        from D:/dev_tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/liquid-3.0.6/lib/liquid/template.rb:222:in `render!'
        from D:/dev_tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/jekyll-3.4.3/lib/jekyll/liquid_renderer/file.rb:28:in `block (2 levels) in render!'
        from D:/dev_tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/jekyll-3.4.3/lib/jekyll/liquid_renderer/file.rb:40:in `measure_bytes'
        from D:/dev_tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/jekyll-3.4.3/lib/jekyll/liquid_renderer/file.rb:27:in `block in render!'
        from D:/dev_tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/jekyll-3.4.3/lib/jekyll/liquid_renderer/file.rb:47:in `measure_time'
        from D:/dev_tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/jekyll-3.4.3/lib/jekyll/liquid_renderer/file.rb:26:in `render!'
        from D:/dev_tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/jekyll-3.4.3/lib/jekyll/renderer.rb:134:in `render_liquid'
        from D:/dev_tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/jekyll-3.4.3/lib/jekyll/renderer.rb:177:in `place_in_layouts'
        from D:/dev_tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/jekyll-3.4.3/lib/jekyll/renderer.rb:91:in `run'
        from D:/dev_tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/jekyll-3.4.3/lib/jekyll/site.rb:463:in `block in render_pages'
        from D:/dev_tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/jekyll-3.4.3/lib/jekyll/site.rb:461:in `each'
        from D:/dev_tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/jekyll-3.4.3/lib/jekyll/site.rb:461:in `render_pages'
        from D:/dev_tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/jekyll-3.4.3/lib/jekyll/site.rb:191:in `render'
        from D:/dev_tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/jekyll-3.4.3/lib/jekyll/site.rb:69:in `process'
        from D:/dev_tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/jekyll-multiple-languages-plugin-1.5.1/lib/jekyll-multiple-languages-plugin.rb:107:in `process'
        from D:/dev_tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/jekyll-3.4.3/lib/jekyll/command.rb:26:in `process_site'
        from D:/dev_tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/jekyll-3.4.3/lib/jekyll/commands/build.rb:63:in `build'
        from D:/dev_tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/jekyll-3.4.3/lib/jekyll/commands/build.rb:34:in `process'
        from D:/dev_tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/jekyll-3.4.3/lib/jekyll/commands/serve.rb:37:in `block (2 levels) in init_with_program'
        from D:/dev_tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        from D:/dev_tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        from D:/dev_tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        from D:/dev_tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        from D:/dev_tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from D:/dev_tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/jekyll-3.4.3/exe/jekyll:13:in `<top (required)>'
        from D:/dev_tools/Ruby23-x64/bin/jekyll:22:in `load'
        from D:/dev_tools/Ruby23-x64/bin/jekyll:22:in `<main>'
```

So how to fix this problem ?

Thanks

**Comment by bgaillard** [comment]
Responding to my own question finally 😄, their are already solutions to this problem here https://github.com/imathis/octopress/issues/413 (and more precisly here https://github.com/imathis/octopress/issues/413#issuecomment-11322912).

In my case I solved it using the following command : `chcp 65001`.

Hope this helps.

**Comment by kleuter** [comment]
It's well documented here:
https://jekyllrb.com/docs/windows/
under "Encoding" section

**Comment by bgaillard** [comment]
@kleuter thanks a lot for this precision https://jekyllrb.com/docs/windows/#encoding !

> I wonder why you post it here, there's nothing related to this plugin

This is because I though my problem was the same as @renefs.

But your right perhaps this is note the same because the error messages are not exactly identic.

On one side we have this error message.

> Liquid Exception: invalid byte sequence in US-ASCII in /_layouts/default.html

And on the other side this one.

> Liquid Exception: incompatible character encodings: UTF-8 and CP850 in /_layouts/default.html
