### ISSUE TITLE
Serve error: undefined method `post_read' for class `Jekyll::Document

### ISSUE THREAD

**Issue by antwal** [Anthony-Gaudino/jekyll-multiple-languages-plugin#92]
Hi, 

I recently tried using this plugin, but unfortunately I see it is not working..

My include gems are: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate-v2
  - jekyll-multiple-languages

The error is:

NameError: undefined method `post_read' for class `Jekyll::Document'
  /Library/Ruby/Gems/2.0.0/gems/jekyll-multiple-languages-2.0.3/lib/jekyll-multiple-languages/document.rb:15:in `<class:Document>'
  /Library/Ruby/Gems/2.0.0/gems/jekyll-multiple-languages-2.0.3/lib/jekyll-multiple-languages/document.rb:3:in `<module:Jekyll>'
  /Library/Ruby/Gems/2.0.0/gems/jekyll-multiple-languages-2.0.3/lib/jekyll-multiple-languages/document.rb:2:in `<top (required)>'
  /Library/Ruby/Gems/2.0.0/gems/jekyll-multiple-languages-2.0.3/lib/jekyll-multiple-languages.rb:3:in `require'
  /Library/Ruby/Gems/2.0.0/gems/jekyll-multiple-languages-2.0.3/lib/jekyll-multiple-languages.rb:3:in `<top (required)>'
  /Library/Ruby/Gems/2.0.0/gems/jekyll-3.3.1/lib/jekyll/external.rb:43:in `require'
  /Library/Ruby/Gems/2.0.0/gems/jekyll-3.3.1/lib/jekyll/external.rb:43:in `block in require_with_graceful_fail'
  /Library/Ruby/Gems/2.0.0/gems/jekyll-3.3.1/lib/jekyll/external.rb:40:in `each'
  /Library/Ruby/Gems/2.0.0/gems/jekyll-3.3.1/lib/jekyll/external.rb:40:in `require_with_graceful_fail'
  /Library/Ruby/Gems/2.0.0/gems/jekyll-3.3.1/lib/jekyll/plugin_manager.rb:27:in `require_gems'
  /Library/Ruby/Gems/2.0.0/gems/jekyll-3.3.1/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
  /Library/Ruby/Gems/2.0.0/gems/jekyll-3.3.1/lib/jekyll/site.rb:111:in `setup'
  /Library/Ruby/Gems/2.0.0/gems/jekyll-3.3.1/lib/jekyll/site.rb:33:in `initialize'
  /Library/Ruby/Gems/2.0.0/gems/jekyll-3.3.1/lib/jekyll/commands/build.rb:28:in `new'
  /Library/Ruby/Gems/2.0.0/gems/jekyll-3.3.1/lib/jekyll/commands/build.rb:28:in `process'
  /Library/Ruby/Gems/2.0.0/gems/jekyll-3.3.1/lib/jekyll/commands/build.rb:16:in `block (2 levels) in init_with_program'
  /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `call'
  /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /Library/Ruby/Gems/2.0.0/gems/jekyll-3.3.1/exe/jekyll:13:in `<top (required)>'
  /usr/bin/jekyll:23:in `load'
  /usr/bin/jekyll:23:in `<top (required)>'

Thanks.

**Comment by antwal** [comment]
Trying a new project, the problem remains the same:

`/Library/Ruby/Gems/2.0.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:94:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'jekyll-multiple-languages'. (Bundler::GemRequireError)
Gem Load Error is: undefined method `post_read' for class `Jekyll::Document'
Backtrace for gem load error is:
/Library/Ruby/Gems/2.0.0/gems/jekyll-multiple-languages-2.0.3/lib/jekyll-multiple-languages/document.rb:15:in `<class:Document>'
/Library/Ruby/Gems/2.0.0/gems/jekyll-multiple-languages-2.0.3/lib/jekyll-multiple-languages/document.rb:3:in `<module:Jekyll>'
/Library/Ruby/Gems/2.0.0/gems/jekyll-multiple-languages-2.0.3/lib/jekyll-multiple-languages/document.rb:2:in `<top (required)>'
/Library/Ruby/Gems/2.0.0/gems/jekyll-multiple-languages-2.0.3/lib/jekyll-multiple-languages.rb:3:in `require'
/Library/Ruby/Gems/2.0.0/gems/jekyll-multiple-languages-2.0.3/lib/jekyll-multiple-languages.rb:3:in `<top (required)>'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `require'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `each'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `block in require'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `each'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `require'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.14.6/lib/bundler.rb:107:in `require'
/Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.3/lib/jekyll/plugin_manager.rb:37:in `require_from_bundler'
/Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.3/exe/jekyll:9:in `<top (required)>'
/usr/bin/jekyll:23:in `load'
/usr/bin/jekyll:23:in `<main>'
Bundler Error Backtrace:
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:90:in `block (2 levels) in require'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `block in require'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.6/lib/bundler.rb:107:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.3/lib/jekyll/plugin_manager.rb:37:in `require_from_bundler'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.3/exe/jekyll:9:in `<top (required)>'
	from /usr/bin/jekyll:23:in `load'
	from /usr/bin/jekyll:23:in `<main>'`

**Comment by antwal** [comment]
Hi,

i have downgrade jekyll to 3.1.3 version and now working

Thanks.
