### ISSUE TITLE
Jekyll 3.5 compatibility

### ISSUE THREAD

**Issue by kleuter** [Anthony-Gaudino/jekyll-multiple-languages-plugin#96]
The plugin is NOT compatible with jekyll 3.5

`Building site for default language: "en" to: G:/Projects/crystalidea.com/_site
Loading translation from file G:/Projects/crystalidea.com/_i18n/en.yml
jekyll 3.5.0 | Error:  undefined method `+' for nil:NilClass`

**Comment by kleuter** [comment]
baseurl: ""
must be define in _config.yml

**Comment by binarious** [comment]
This results in
```
NoMethodError: undefined method `[]=' for nil:NilClass
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-multiple-languages-plugin-1.5.1/lib/jekyll-multiple-languages-plugin.rb:38:in `block (2 levels) in <module:Jekyll>'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-multiple-languages-plugin-1.5.1/lib/jekyll-multiple-languages-plugin.rb:34:in `delete_if'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-multiple-languages-plugin-1.5.1/lib/jekyll-multiple-languages-plugin.rb:34:in `block in <module:Jekyll>'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.5.1/lib/jekyll/hooks.rb:98:in `block in trigger'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.5.1/lib/jekyll/hooks.rb:97:in `each'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.5.1/lib/jekyll/hooks.rb:97:in `trigger'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.5.1/lib/jekyll/site.rb:197:in `render'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.5.1/lib/jekyll/site.rb:73:in `process'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-multiple-languages-plugin-1.5.1/lib/jekyll-multiple-languages-plugin.rb:125:in `block in process'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-multiple-languages-plugin-1.5.1/lib/jekyll-multiple-languages-plugin.rb:116:in `each'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-multiple-languages-plugin-1.5.1/lib/jekyll-multiple-languages-plugin.rb:116:in `process'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.5.1/lib/jekyll/command.rb:26:in `process_site'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.5.1/lib/jekyll/commands/build.rb:63:in `build'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.5.1/lib/jekyll/commands/build.rb:34:in `process'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.5.1/lib/jekyll/commands/serve.rb:40:in `block (3 levels) in init_with_program'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.5.1/lib/jekyll/commands/serve.rb:40:in `each'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.5.1/lib/jekyll/commands/serve.rb:40:in `block (2 levels) in init_with_program'
  /usr/local/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /usr/local/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /usr/local/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /usr/local/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /usr/local/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.5.1/exe/jekyll:13:in `<top (required)>'
  /usr/local/bin/jekyll:23:in `load'
  /usr/local/bin/jekyll:23:in `<top (required)>'
```
for me.
